version: '2'

services:
  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./databaseScript.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_PASSWORD=${DB_PASSWORD}

  conushop:
    image: hitalos/laravel:latest
    ports:
        - 80:80
    volumes:
        - ./:/var/www
    links:
        - mariadb
    environment:
        - DB_HOST:mariadb
        - DB_DATABASE:${DB_DATABASE}
        - DB_USERNAME:${DB_USERNAME}
        - DB_PASSWORD:${DB_PASSWORD}
        - DB_CONNECTION:mysql
